services:
  mysql:
    image: mysql
    ports:
      - "3308:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=User_todo
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=db_list_todo
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    
    